package eventosTela;

public enum EventosTela {


    USUARIO_AUTENTICADO_COMUM,
    USUARIO_AUTENTICADO_ADMIN,
    CADASTRO_REALIZADO_COM_SUCESSO,
    USUARIO_EXCLUIDO_COM_SUCESSO, DELETAR_PRESENTER
}
