/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package views;

import javax.swing.*;

/**
 *
 * @author marce
 */
public class TelaAdminView extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(TelaAdminView.class.getName());

    /**
     * Creates new form TelaAdminView
     */
    public TelaAdminView() {
        initComponents();


        tabelaUsuarios.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);

        setVisible(true);
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        nomeUsuarioLabel = new javax.swing.JLabel();
        tipoUsuarioLabel = new javax.swing.JLabel();
        btnNotificacoes = new javax.swing.JButton();
        btnNovo = new javax.swing.JButton();
        btnVisualizar = new javax.swing.JButton();
        btnSair = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        nomeUsuarioText = new javax.swing.JTextField();
        btnBuscar = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelaUsuarios = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        btnEnviarNotificacoes = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("TelaUsuario");

        nomeUsuarioLabel.setText("valor1");

        tipoUsuarioLabel.setText("tippo");

        btnNotificacoes.setText(" 0 Notificações Não Lidas");
        btnNotificacoes.setAlignmentX(20.0F);
        btnNotificacoes.setAlignmentY(2.0F);
        btnNotificacoes.setName(""); // NOI18N

        btnNovo.setText("Novo");

        btnVisualizar.setText("Visualizar");

        btnSair.setText("Sair");

        jLabel9.setText("Buscar Por Nome:");

        btnBuscar.setText("Buscar");
        btnBuscar.setToolTipText("");

        tabelaUsuarios.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nome", "Data Cadastro", "Notificações Enviadas", "Notificações Lidas"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tabelaUsuarios.setToolTipText("");
        jScrollPane1.setViewportView(tabelaUsuarios);

        jScrollPane2.setViewportView(jScrollPane1);

        jLabel1.setText("Seleciona uma linha da tabela para executar o comando: Visualizar no botão abaixo.");

        btnEnviarNotificacoes.setText("Enviar Notificações");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(63, 63, 63)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(nomeUsuarioLabel)
                        .addGap(84, 84, 84)
                        .addComponent(tipoUsuarioLabel))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(btnNovo)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(btnVisualizar)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(btnSair)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btnEnviarNotificacoes))
                                .addComponent(jLabel1))
                            .addGap(18, 18, 18)
                            .addComponent(btnNotificacoes, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel9)
                            .addGap(18, 18, 18)
                            .addComponent(nomeUsuarioText)
                            .addGap(18, 18, 18)
                            .addComponent(btnBuscar))
                        .addComponent(jScrollPane2)))
                .addContainerGap(63, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(nomeUsuarioText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBuscar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 9, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 315, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnNovo)
                    .addComponent(btnVisualizar)
                    .addComponent(btnSair)
                    .addComponent(btnNotificacoes)
                    .addComponent(btnEnviarNotificacoes))
                .addGap(46, 46, 46)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(nomeUsuarioLabel)
                    .addComponent(tipoUsuarioLabel))
                .addGap(13, 13, 13))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new TelaAdminView().setVisible(true));
    }

    public JLabel getNomeUsuarioLabel() {
        return nomeUsuarioLabel;
    }

    public JTable getTabelaUsuarios() {
        return tabelaUsuarios;
    }

    public JButton getBtnEnviarNotificacoes() {
        return btnEnviarNotificacoes;
    }

    public String getNomeUsuarioText() {
        return nomeUsuarioText.getText();
    }

    public void setQtdNotificacoesNLidas(int qtd){
        btnNotificacoes.setText(Integer.toString(qtd) + "Notificaações nãao lidas");
    }
    public JLabel getTipoUsuarioLabel() {
        return tipoUsuarioLabel;
    }

    public JButton getBtnBuscar() {
        return btnBuscar;
    }

    public JButton getBtnNotificacoes() {
        return btnNotificacoes;
    }

    public JButton getBtnNovo() {
        return btnNovo;
    }

    public JButton getBtnSair() {
        return btnSair;
    }

    public JButton getBtnVisualizar() {
        return btnVisualizar;
    }
    
    public void mudarNomeLabel(String nome){
        nomeUsuarioLabel.setText(nome);
    }
    
    public void mudarTipoLabel(String tipo){
        tipoUsuarioLabel.setText(tipo);
    }
    
    public int obterLinhaSelecionadaNaTabela(){
        return this.tabelaUsuarios.getSelectedRow();
    }
    
    

    public void mostrarMensagem(String mensagem){
        JOptionPane.showMessageDialog(this, mensagem);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnEnviarNotificacoes;
    private javax.swing.JButton btnNotificacoes;
    private javax.swing.JButton btnNovo;
    private javax.swing.JButton btnSair;
    private javax.swing.JButton btnVisualizar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel nomeUsuarioLabel;
    private javax.swing.JTextField nomeUsuarioText;
    private javax.swing.JTable tabelaUsuarios;
    private javax.swing.JLabel tipoUsuarioLabel;
    // End of variables declaration//GEN-END:variables
}
