/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package views;

import javax.swing.*;

/**
 *
 * @author marce
 */
public class TelaCadastroView extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(TelaCadastroView.class.getName());

    /**
     * Creates new form TelaCadastroView
     */
    public TelaCadastroView() {
        initComponents();
        setVisible(true);
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        usuarioLabel = new javax.swing.JLabel();
        usuarioText = new javax.swing.JTextField();
        senhaLabel = new javax.swing.JLabel();
        btnCancelar = new javax.swing.JButton();
        btnCadastrar = new javax.swing.JButton();
        senhaNovamenteLabel = new javax.swing.JLabel();
        senhaText = new javax.swing.JPasswordField();
        senhaNovamenteText = new javax.swing.JPasswordField();
        emailLabel = new javax.swing.JLabel();
        emailText = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        autenticadoCheckBox = new javax.swing.JCheckBox();
        adminCheckBox = new javax.swing.JCheckBox();
        checkBoxLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("TelaCadastro");

        usuarioLabel.setText("Usuario:");

        usuarioText.setToolTipText("");
        usuarioText.addActionListener(this::usuarioTextActionPerformed);

        senhaLabel.setText("Senha:");

        btnCancelar.setText("Cancelar");

        btnCadastrar.setText("Cadastrar");
        btnCadastrar.addActionListener(this::btnCadastrarActionPerformed);

        senhaNovamenteLabel.setText("Senha Novamente:");

        emailLabel.setText("Email:");

        emailText.setToolTipText("");
        emailText.addActionListener(this::emailTextActionPerformed);

        jLabel1.setFont(new java.awt.Font("Leelawadee UI", 1, 14)); // NOI18N
        jLabel1.setText("CADASTRO");

        autenticadoCheckBox.setText("Autenticado");

        adminCheckBox.setText("Admin");

        checkBoxLabel.setText("Marque os campos abaixo para decidir se o usuário deve ser ou estar:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(224, 224, 224)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(45, 45, 45)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(senhaLabel)
                                .addComponent(usuarioLabel)
                                .addComponent(emailLabel)
                                .addComponent(senhaNovamenteLabel)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(btnCancelar)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 276, Short.MAX_VALUE)
                                    .addComponent(btnCadastrar))
                                .addComponent(usuarioText)
                                .addComponent(senhaNovamenteText)
                                .addComponent(emailText)
                                .addComponent(senhaText))
                            .addComponent(checkBoxLabel)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(124, 124, 124)
                                .addComponent(adminCheckBox)
                                .addGap(26, 26, 26)
                                .addComponent(autenticadoCheckBox)))))
                .addContainerGap(45, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(usuarioLabel)
                .addGap(10, 10, 10)
                .addComponent(usuarioText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(emailLabel)
                .addGap(10, 10, 10)
                .addComponent(emailText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(senhaLabel)
                .addGap(10, 10, 10)
                .addComponent(senhaText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(senhaNovamenteLabel)
                .addGap(10, 10, 10)
                .addComponent(senhaNovamenteText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 20, Short.MAX_VALUE)
                .addComponent(checkBoxLabel)
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(autenticadoCheckBox)
                    .addComponent(adminCheckBox))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCancelar)
                    .addComponent(btnCadastrar))
                .addGap(34, 34, 34))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void usuarioTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_usuarioTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_usuarioTextActionPerformed

    private void btnCadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadastrarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCadastrarActionPerformed

    private void emailTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_emailTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_emailTextActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new TelaCadastroView().setVisible(true));
    }

    
    public void iniciarVisibilidade(boolean eVisivel){
        setVisible(eVisivel);
    }

    public JButton getBtnCadastrar() {
        return btnCadastrar;
    }

    public JButton getBtnCancelar() {
        return btnCancelar;
    }

    public JLabel getSenhaLabel() {
        return senhaLabel;
    }

    public char[] getSenhaNovamenteText() {
        return senhaNovamenteText.getPassword();
    }

    public char[] getSenhaText() {
        return senhaText.getPassword();
    }
    

    public String getUsuarioText() {
        return usuarioText.getText();
    }

    public String getEmailText() {
        return emailText.getText();
    }


    public void limparCampos(){
        usuarioText.setText("");
        emailText.setText("");
        senhaText.setText("");
        senhaNovamenteText.setText("");
        adminCheckBox.setSelected(false);
        autenticadoCheckBox.setSelected(false);
    }

    public void mostrarMensagem(String mensagem){
        JOptionPane.showMessageDialog(this, mensagem);
    }
    
    public void desabilitarBtnAdminCheckBox(){
        adminCheckBox.setEnabled(false);
    }
    public void desabilitarBtnAutenticadoCheckBox(){
        autenticadoCheckBox.setEnabled(false);
    }

    public JCheckBox getAdminCheckBox() {
        return adminCheckBox;
    }

    public JCheckBox getAutenticadoCheckBox() {
        return autenticadoCheckBox;
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox adminCheckBox;
    private javax.swing.JCheckBox autenticadoCheckBox;
    private javax.swing.JButton btnCadastrar;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JLabel checkBoxLabel;
    private javax.swing.JLabel emailLabel;
    private javax.swing.JTextField emailText;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel senhaLabel;
    private javax.swing.JLabel senhaNovamenteLabel;
    private javax.swing.JPasswordField senhaNovamenteText;
    private javax.swing.JPasswordField senhaText;
    private javax.swing.JLabel usuarioLabel;
    private javax.swing.JTextField usuarioText;
    // End of variables declaration//GEN-END:variables
    


}
