/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package views;

import javax.swing.JButton;
import javax.swing.JOptionPane;
import javax.swing.JTabbedPane;
import javax.swing.JTable;
import javax.swing.ListSelectionModel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author marce
 */
public class TelaNotificacoesView extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(TelaNotificacoesView.class.getName());
    private  DefaultTableModel modeloTabelaNotificacoesNaoLidas;
    /**
     * Creates new form TelaNotificacoesView
     */
    public TelaNotificacoesView() {
        initComponents();
        setVisible(true);
        setLocationRelativeTo(null);
        tabelaNotificacoesNaoLidas.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
        modeloTabelaNotificacoesNaoLidas = (DefaultTableModel) tabelaNotificacoesNaoLidas.getModel();



    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        abasPaineis = new javax.swing.JTabbedPane();
        painelNotificacoesNaoLidas = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelaNotificacoesNaoLidas = new javax.swing.JTable();
        btnLer = new javax.swing.JButton();
        btnSairNotificacoesNLidas = new javax.swing.JButton();
        painelNotificacoesLidas = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tabelaNotificacoesNaoLidas1 = new javax.swing.JTable();
        btnSairNotificacoesLidas = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        abasPaineis.setToolTipText("");

        painelNotificacoesNaoLidas.setToolTipText("");

        tabelaNotificacoesNaoLidas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Remetente", "Mensagem"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tabelaNotificacoesNaoLidas);

        btnLer.setText("Ler");

        btnSairNotificacoesNLidas.setText("Sair");

        javax.swing.GroupLayout painelNotificacoesNaoLidasLayout = new javax.swing.GroupLayout(painelNotificacoesNaoLidas);
        painelNotificacoesNaoLidas.setLayout(painelNotificacoesNaoLidasLayout);
        painelNotificacoesNaoLidasLayout.setHorizontalGroup(
            painelNotificacoesNaoLidasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelNotificacoesNaoLidasLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 671, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(25, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, painelNotificacoesNaoLidasLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnSairNotificacoesNLidas)
                .addGap(146, 146, 146)
                .addComponent(btnLer)
                .addGap(219, 219, 219))
        );
        painelNotificacoesNaoLidasLayout.setVerticalGroup(
            painelNotificacoesNaoLidasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelNotificacoesNaoLidasLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(painelNotificacoesNaoLidasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnLer)
                    .addComponent(btnSairNotificacoesNLidas))
                .addContainerGap(14, Short.MAX_VALUE))
        );

        abasPaineis.addTab("Notificações Não Lidas", painelNotificacoesNaoLidas);

        painelNotificacoesLidas.setToolTipText("");

        tabelaNotificacoesNaoLidas1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Remetente", "Mensagem"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(tabelaNotificacoesNaoLidas1);

        btnSairNotificacoesLidas.setText("Sair");

        javax.swing.GroupLayout painelNotificacoesLidasLayout = new javax.swing.GroupLayout(painelNotificacoesLidas);
        painelNotificacoesLidas.setLayout(painelNotificacoesLidasLayout);
        painelNotificacoesLidasLayout.setHorizontalGroup(
            painelNotificacoesLidasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelNotificacoesLidasLayout.createSequentialGroup()
                .addGroup(painelNotificacoesLidasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(painelNotificacoesLidasLayout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 671, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(painelNotificacoesLidasLayout.createSequentialGroup()
                        .addGap(312, 312, 312)
                        .addComponent(btnSairNotificacoesLidas)))
                .addContainerGap(25, Short.MAX_VALUE))
        );
        painelNotificacoesLidasLayout.setVerticalGroup(
            painelNotificacoesLidasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelNotificacoesLidasLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnSairNotificacoesLidas)
                .addContainerGap(14, Short.MAX_VALUE))
        );

        abasPaineis.addTab("Notificacoes Lidas", painelNotificacoesLidas);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(abasPaineis)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(abasPaineis)
        );

        abasPaineis.getAccessibleContext().setAccessibleName("NotificacoesLidas");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new TelaNotificacoesView().setVisible(true));
    }

    public JTabbedPane getAbasPaineis() {
        return abasPaineis;
    }

    public JButton getBtnLer() {
        return btnLer;
    }

    public JButton getBtnSairNotificacoesNLidas() {
        return btnSairNotificacoesNLidas;
    }

    public JButton getBtnSairNotificacoesLidas() {
        return btnSairNotificacoesLidas;
    }

    public void inserirDadoNaTabelaNotificacoesNaoLida(String remetente, String mensagem) {
        modeloTabelaNotificacoesNaoLidas.addRow(new Object[]{
                remetente, mensagem
        });
    }

    public void inserirDadoNaTabelaNotificacoesLida(String remetente, String mensagem) {
        DefaultTableModel modelo = (DefaultTableModel) tabelaNotificacoesNaoLidas1.getModel();
        modelo.addRow(new Object[]{remetente, mensagem});
    }

    public void limparTabelaNotificacoesNaoLidas() {
        modeloTabelaNotificacoesNaoLidas.setRowCount(0);
    }

    public void limparTabelaNotificacoesLidas() {
        DefaultTableModel modelo = (DefaultTableModel) tabelaNotificacoesNaoLidas1.getModel();
        modelo.setRowCount(0);
    }

    public JTable getTabelaNotificacoesNaoLidas() {
        return tabelaNotificacoesNaoLidas;
    }

    public void mostrarMensagem(String mensagem) {
        JOptionPane.showMessageDialog(this, mensagem);
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTabbedPane abasPaineis;
    private javax.swing.JButton btnLer;
    private javax.swing.JButton btnSairNotificacoesLidas;
    private javax.swing.JButton btnSairNotificacoesNLidas;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JPanel painelNotificacoesLidas;
    private javax.swing.JPanel painelNotificacoesNaoLidas;
    private javax.swing.JTable tabelaNotificacoesNaoLidas;
    private javax.swing.JTable tabelaNotificacoesNaoLidas1;
    // End of variables declaration//GEN-END:variables
}
