/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package views;

import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JTextField;

/**
 *
 * @author marce
 */
public class TelaVisualizaView extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(TelaVisualizaView.class.getName());

    /**
     * Creates new form TelaVisualizaView
     */
    public TelaVisualizaView() {
        initComponents();
        setLocationRelativeTo(null);
        setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnExcluir = new javax.swing.JButton();
        btnEditar = new javax.swing.JButton();
        nomeLabel = new javax.swing.JLabel();
        btnAutenticar = new javax.swing.JButton();
        titulo = new javax.swing.JLabel();
        dataCadastroLabel = new javax.swing.JLabel();
        notificacoesLidasLabel = new javax.swing.JLabel();
        notificacoesNaoLidasLabel = new javax.swing.JLabel();
        dadoNomeLabel = new javax.swing.JLabel();
        dadoDataCadastroLabel = new javax.swing.JLabel();
        dadoNotificacoesLidasLabel = new javax.swing.JLabel();
        dadoNotificacoesNaoLidaLabel = new javax.swing.JLabel();
        dadoEmailLabel = new javax.swing.JLabel();
        emailLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Visualização");
        setBackground(new java.awt.Color(255, 255, 255));
        setBounds(new java.awt.Rectangle(0, 0, 0, 0));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        btnExcluir.setText("Excluir");
        btnExcluir.addActionListener(this::btnExcluirActionPerformed);

        btnEditar.setText("Editar");

        nomeLabel.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        nomeLabel.setText("Nome:");

        btnAutenticar.setText("Autenticar");

        titulo.setFont(new java.awt.Font("Leelawadee UI", 1, 14)); // NOI18N
        titulo.setText("Visualizar Informações");

        dataCadastroLabel.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        dataCadastroLabel.setText("Data Cadastro:");

        notificacoesLidasLabel.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        notificacoesLidasLabel.setText("Notificações Lidas:");

        notificacoesNaoLidasLabel.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        notificacoesNaoLidasLabel.setText("Notificações Não Lidas:");

        dadoNomeLabel.setText("fdafad");
        dadoNomeLabel.setEnabled(false);

        dadoDataCadastroLabel.setText("dfafadf");
        dadoDataCadastroLabel.setEnabled(false);

        dadoNotificacoesLidasLabel.setText("adfaf");
        dadoNotificacoesLidasLabel.setEnabled(false);

        dadoNotificacoesNaoLidaLabel.setText("afda");
        dadoNotificacoesNaoLidaLabel.setToolTipText("");
        dadoNotificacoesNaoLidaLabel.setEnabled(false);

        dadoEmailLabel.setText("adfaf");
        dadoEmailLabel.setEnabled(false);

        emailLabel.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        emailLabel.setText("Email:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(titulo)
                .addGap(190, 190, 190))
            .addGroup(layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnExcluir)
                        .addGap(18, 18, 18)
                        .addComponent(btnEditar)
                        .addGap(18, 18, 18)
                        .addComponent(btnAutenticar))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(nomeLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(dadoNomeLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 411, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(notificacoesNaoLidasLabel)
                        .addGap(18, 18, 18)
                        .addComponent(dadoNotificacoesNaoLidaLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(dataCadastroLabel)
                        .addGap(18, 18, 18)
                        .addComponent(dadoDataCadastroLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 363, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(notificacoesLidasLabel)
                        .addGap(18, 18, 18)
                        .addComponent(dadoNotificacoesLidasLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(emailLabel)
                        .addGap(18, 18, 18)
                        .addComponent(dadoEmailLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 411, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(39, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(titulo)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nomeLabel)
                    .addComponent(dadoNomeLabel))
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(emailLabel)
                    .addComponent(dadoEmailLabel))
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(dataCadastroLabel)
                    .addComponent(dadoDataCadastroLabel))
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(notificacoesLidasLabel)
                    .addComponent(dadoNotificacoesLidasLabel))
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(notificacoesNaoLidasLabel)
                    .addComponent(dadoNotificacoesNaoLidaLabel))
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnExcluir)
                    .addComponent(btnEditar)
                    .addComponent(btnAutenticar))
                .addContainerGap(40, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcluirActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnExcluirActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new TelaVisualizaView().setVisible(true));
    }

    public JButton getBtnAutenticar() {
        return btnAutenticar;
    }

    public JButton getBtnEditar() {
        return btnEditar;
    }

    public JButton getBtnExcluir() {
        return btnExcluir;
    }

    public void setTextoDadoDataCadastroLabel(String dadoDataCadastroLabel) {
        this.dadoDataCadastroLabel.setText(dadoDataCadastroLabel); 
    }
    public void setTextoDadoEmailLabel(String dadoEmailLabel){
        this.dadoEmailLabel.setText(dadoEmailLabel);
    }

    public void setTextoDadoNomeLabel(String dadoNomeLabel) {
        this.dadoNomeLabel.setText(dadoNomeLabel);
    }

    public void setTextoDadoNotificacoesLidasLabel(String dadoNotificacoesLidasLabel) {
        this.dadoNotificacoesLidasLabel.setText(dadoNotificacoesLidasLabel);
    }

    public void setTextoDadoNotificacoesNaoLidaLabel(String dadoNotificacoesNaoLidaLabel) {
        this.dadoNotificacoesNaoLidaLabel.setText(dadoNotificacoesNaoLidaLabel);
    }
    
    


    
    
    
  
    
    
    public void mostrarMensagem(String mensagem){
        JOptionPane.showMessageDialog(null, mensagem);
    }
    
    public int confirmarAcao(String mensagem){
        return JOptionPane.showOptionDialog(
            this,
            mensagem,
            "Confirmação",
            JOptionPane.YES_NO_OPTION,
            JOptionPane.QUESTION_MESSAGE,
            null,
            new Object[]{"Sim", "Não"},
            "Não"
        );
    }

    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAutenticar;
    private javax.swing.JButton btnEditar;
    private javax.swing.JButton btnExcluir;
    private javax.swing.JLabel dadoDataCadastroLabel;
    private javax.swing.JLabel dadoEmailLabel;
    private javax.swing.JLabel dadoNomeLabel;
    private javax.swing.JLabel dadoNotificacoesLidasLabel;
    private javax.swing.JLabel dadoNotificacoesNaoLidaLabel;
    private javax.swing.JLabel dataCadastroLabel;
    private javax.swing.JLabel emailLabel;
    private javax.swing.JLabel nomeLabel;
    private javax.swing.JLabel notificacoesLidasLabel;
    private javax.swing.JLabel notificacoesNaoLidasLabel;
    private javax.swing.JLabel titulo;
    // End of variables declaration//GEN-END:variables
}
